= Camel-Quarkus Demo

== How to Prepare the Demo

[source,shell]
----

# Open terminator and configure the local rest demo
cd ~/dev/demos/camel-quarkus-demos/integration-in-the-cloud-era-with-camel-quarkus/rest-to-nats-demo/
git checkout -- .
# Split window horizontally, then horizontally, and run below command in each shell
main_upstream
# Then run each command below in its own shell
./start-nats.sh
http localhost:8080/steps
mvn quarkus:dev (can kill it before demo)
# Tune the zoom in each shell (CTRL + scroll as necessary)

# In eclipse Open rest-to-nats-demo/CamelRoutes,Step2Bean,StepsRouteTest,Configurations,application.properties
# In eclipse Open by-cq-knative-jvm-mode/MyRoutBuilder.java
# Execute StepsRouteTest Junit test once, at this stage it should fail with ACTUAL="STEP 1"
# Zoom in eclipse editor (CTRL/SHIFT/+ 5 times so that we have ~85 chars per line)
# In openshift console, prepare Serverless/Services with namespace default (we should see the 4 knative services)
# Configure audio input/output to headset
# Copy paste tiny urls so that we can send it very early
# Configure display on a single screen (like for Apache CON @Home & JavaLand)

# In workspace 2: SUPER+PUAGE_UP/DOWN to change workspace, Open slides:
# ~/dev/demos/camel-quarkus-demos/integration-in-the-cloud-era-with-camel-quarkus/Integration\ In\ The\ Cloud\ Era\ With\ Camel\ Quarkus.odp

----

== How to Run the Demo

[source,shell]
----
# Take care of possible lags = audio/video shift, it's worth waiting few seconds so that everyone could see commands output
# Copy paste tiny urls in chat/browser/presentation system
https://tinyurl.com/vpyfr9xb (Camel Quarkus website)
https://tinyurl.com/wpa7wvp9 (Quarkus website)
https://tinyurl.com/2cm7886s (Building a native executable)
https://tinyurl.com/38yyrx84 (GraalVM Native Image)
https://tinyurl.com/7hruukyd (Demo with sources on github)

# Speech: Slides about Presenter, Plan, Camel Reminder, Quarkus reminder

# Show the rest DSL in Java
# In a first shell
mvn quarkus:dev
# Invoke the service from the middle shell output "STEP 1"
http localhost:8080/steps

# Uncomment bean in route definition, mention the EndpointRouteBuilder syntax
# Invoke the service from the middle shell output "STEP 1 - STEP 2"
http localhost:8080/steps

# Show in StepsRouteTest how to override the bean in a test
# Run the JUnit test from quarkus:dev (by pressing 'r' in the quarkus:dev console)

# Uncomment log in route definition
# Invoke the service from the middle shell output logs with MEP and body type
http localhost:8080/steps

# Uncomment `logComponent.setExchangeFormatter(formatter);` in `Configurations.onComponentAdd` method (camel component tuning via java code)
# Invoke the service from the middle shell output logs without MEP and body type
http localhost:8080/steps

# Uncomment the nats line in route definition, notice that type safe endpoint dsl
# quarkus:dev can't start
# Uncomment nats.servers line in application.properties (camel component tuning via properties)
# Invoke, and show the logs from nats server
http localhost:8080/steps

# Now let's try in native mode
mvn clean package -D native
# Speech: Pave the 1 minutes with the slide comparing JVM vs native
# Speech: Mention that quarkus is already doing fine in JVM
# Speech: Mention that the 3s long configuration is done at build time

target/rest-to-nats-demo-1.0.0-SNAPSHOT-runner
# Oops not running, we need to explicitly embed some resources
# So uncomment 'quarkus.camel.native.resources.include-patterns' in application.properties
mvn clean package -D native
# Speech: Pave the 3 minutes with slides Native mode (how great), Native mode (how complex)
target/rest-to-nats-demo-1.0.0-SNAPSHOT-runner

# Move to knative terminator and present the environment
# Speech: Show a knative service in eclipse, mention kubernetes extension
# Speech: OpenShift cluster = kubernetes with goodies
# Speech: Goodies like serverless tab => 4 services in default namespace
# Speech: bottom shell, quota expand later, and no pods => knative scales to zero

hello-jvm
# On demand provisioning, first request served in ~6s

hello-native
# Speech: We save the 3s from the static initializer, so we have seen the boot time effect
# Speech: Wait for knative to scale to zero
# Speech: Explain mem quota, then hello-jvm, at 30s launch bye-jvm, oh needs to wait (it's either delay or dollar)
# Speech: hello-native, bye-native => we have a better densification

# Speech: Slides about conclusion, it's all about, thanks

----------------------------------------------------------------------------------------------------------------------

Raw notes for demo/improvements:

@TODO: Migrate to newer nats image
@TODO: Fake the native compilation (it disturbs the demo, for instance it competes with resources from the conferencing system, could be slower)

TODO in another demo:

Find below how to show resources consumption for containers:
watch oc exec hello-cq-knative-native-mode-lswdr-3-deployment-fc89bdd8-9jlc5 cat /sys/fs/cgroup/memory/memory.usage_in_bytes
 50999808 ( 48.64 MiB) in native
613645120 (585.22 MiB) in jvm
To get the sidecar usage, you need to add "-c queue-proxy"
watch oc exec hello-cq-knative-native-mode-yylnv-3-deployment-7fdd977b8f2x2bx -c queue-proxy cat /sys/fs/cgroup/memory/memory.usage_in_bytes

TIPS to create a gif file from images:
ffmpeg -framerate 0.5 -pattern_type glob -i "Screenshot from 2021-05-07-15h-Getting Further With Camel on Quarkus.mkv - *.png" -s 960x540 demo.gif
